# **Первая часть**

__1.__ Решить систему уравнений методом Гаусса:

$$\begin{cases}
x_{1}+x_{2}-x_{3}-2x_{4}=0, \\
2x_{1}+x_{2}-x_{3}+x_{4}=-2, \\
x_{1}+x_{2}-3x_{3}+x_{4}=4.
\end{cases}$$

Решение: 

$$\begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 & -2 \\ 
2 & 1 & -1 & 1\\ 
1 & 1 & -3 & 1
\end{matrix}\right|
\begin{matrix}
0\\ 
-2\\
4
\end{matrix}
\end{pmatrix}.$$

Вычтем из третьей строки первую, и из второй строки первую, умноженную на 2:

$$\begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 & -2 \\ 
0 & -1 & 1 & 5\\ 
0 & 0 & -2 & 3
\end{matrix}\right|
\begin{matrix}
0\\ 
-2\\
4
\end{matrix}
\end{pmatrix}.$$

можно рассматривать в качестве _свободного_ параметра $x_{4}=c$. Тогда, выражая остальные переменные через $c$, получим:

$$x_{4}=c,$$
$$-2x_{3}+3c=4 \; \Leftrightarrow \; x_{3}=(3c-4)/2,$$
$$-x_{2} + (3c-4)/2 + 5c= -2 \; \Leftrightarrow \; x_{2}=13c/2.$$
$$x_{1} + 13c/2 - (3c-4)/2 -2c= 0 \; \Leftrightarrow \; x_{1}=-3c-2.$$


__2.__ Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений:

   а) $\begin{cases}
3x_{1}-x_{2}+x_{3}=4, \\
2x_{1}-5x_{2}-3x_{3}=-17, \\
x_{1}+x_{2}-x_{3}=0;
\end{cases}$
    
   б) $\begin{cases}
2x_{1}-4x_{2}+6x_{3}=1, \\
x_{1}-2x_{2}+3x_{3}=-2, \\
3x_{1}-6x_{2}+9x_{3}=5;
\end{cases}$
    
   в) $\begin{cases}
x_{1}+2x_{2}+5x_{3}=4, \\
3x_{1}+x_{2}-8x_{3}=-2. 
\end{cases}$

a)
$$\begin{pmatrix}
\left.\begin{matrix}
3 & -1 & 1 \\ 
2 & -5 & -3 \\ 
1 & 1 & -1
\end{matrix}\right|
\begin{matrix}
4\\ 
-17\\
0
\end{matrix}
\end{pmatrix} \Leftrightarrow 
\begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 \\ 
0 & -7 & -1 \\ 
0 & -4 & 4
\end{matrix}\right|
\begin{matrix}
0\\ 
-17\\
4
\end{matrix}
\end{pmatrix}\Leftrightarrow 
\begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 \\ 
0 & 4 & -4 \\ 
0 & -7 & -1
\end{matrix}\right|
\begin{matrix}
0\\ 
-4\\
-17
\end{matrix}
\end{pmatrix}\Leftrightarrow 
\begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 \\ 
0 & 1 & -1 \\ 
0 & 0 & -8
\end{matrix}\right|
\begin{matrix}
0\\ 
-1\\
-24
\end{matrix}
\end{pmatrix}$$

Система совместа, имеет единственное решение

б)
$$\begin{pmatrix}
\left.\begin{matrix}
2 & -4 & 6 \\ 
1 & -2 & 3 \\ 
3 & -6 & 9
\end{matrix}\right|
\begin{matrix}
1\\ 
-2\\
5
\end{matrix}
\end{pmatrix}$$ 

Сложим первые две строки и отнимем от третьей:

$$
\begin{pmatrix}
\left.\begin{matrix}
2 & -4 & 6 \\ 
1 & -2 & 3 \\ 
0 & 0 & 0
\end{matrix}\right|
\begin{matrix}
1\\ 
-2\\
6
\end{matrix}
\end{pmatrix}$$

Система несовместна

в)
$$\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 5 \\ 
3 & 1 & -8
\end{matrix}\right|
\begin{matrix}
4\\ 
-2
\end{matrix}
\end{pmatrix}$$ 

Отнимем от третьей строки первую, умноженную на 3:

$$
\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 5 \\ 
0 & -5 & -23
\end{matrix}\right|
\begin{matrix}
4\\ 
-14
\end{matrix}
\end{pmatrix}
$$

Система совместа, имеет бесконечное количество решений

__3.__ Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений, заданная расширенной матрицей

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 3 & -2 & 4\\ 
0 & 5 & 0 & 1\\ 
0 & 0 & 3 & 0\\ 
0 & 0 & 0 & 2
\end{matrix}\right|
\begin{matrix}
3\\ 
2\\
4\\
1
\end{matrix}
\end{pmatrix}.$$

Решение:

Ранг матрицы равен 4. Последняя строка имее решение. Система совместна и имеет единственное решение

__4.__ Дана система линейных уравнений, заданная расширенной матрицей

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{matrix}\right|
\begin{matrix}
a\\ 
b\\
c
\end{matrix}
\end{pmatrix}.$$

Найти соотношение между параметрами $a$, $b$ и $c$, при которых система является несовместной.

$$\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{matrix}\right|
\begin{matrix}
a\\ 
b\\
c
\end{matrix}
\end{pmatrix} \Leftrightarrow
\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
0 & -3 & -6\\ 
0 & -6 & -12
\end{matrix}\right|
\begin{matrix}
a\\ 
b-4a\\
c-7a
\end{matrix}
\end{pmatrix}$$

Чтобы система было несовместа, небходимо, чтобы свободные члены нижних двух строк не были подобны с коэффицтентом 2 (так как 2 нижние строки подобны с коэфициентом 2):
$$2(b-4a)  \neq c-7a \Leftrightarrow 2b-c \neq a$$

# **Вторая часть**

__1.__ Решить систему уравнений методом Крамера:

   а) $\begin{cases}
x_{1}-2x_{2}=1 \\
3x_{1}-4x_{2}=7
\end{cases}$
    
   б) $\begin{cases}
2x_{1}-x_{2}+5x_{3}=10 \\
x_{1}+x_{2}-3x_{3}=-2 \\
2x_{1}+4x_{2}+x_{3}=1
\end{cases}$

Решение:

а) $$detA=\begin{vmatrix}
1 & -2 \\ 
3 & -4 
\end{vmatrix}=
1*(-4) - (-2)*3 = 2\neq 0,$$

$$detA_1=\begin{vmatrix}
1 & -2 \\ 
7 & -4 
\end{vmatrix}=
1*(-4) - (-2)*7 = 10,$$

$$detA_2=\begin{vmatrix}
1 & 1 \\ 
3 & 7 
\end{vmatrix}=
1*7 - 1*3 = 4.$$

Найдем решение

$$x_{1} = \frac{detA_{1}}{detA} = \frac{10}{2}=5,$$

$$x_{2} = \frac{detA_{2}}{detA} = \frac{4}{2}=2$$

б)
$$detA=\begin{vmatrix}
2 & -1 & 5\\ 
1 & 1 & -3\\ 
2 & 4 & 1
\end{vmatrix}=
2\begin{vmatrix}
1 & -3\\ 
4 & 1 
\end{vmatrix}-
\begin{vmatrix}
-1 & 5\\ 
4 & 1 
\end{vmatrix}+
2\begin{vmatrix}
-1 & 5 \\ 
1 & -3
\end{vmatrix}=2(1 \cdot 1-3\cdot (-4))-(-1\cdot 1-5\cdot 4)+2(-1\cdot (-3)-5\cdot 1)= 26 + 21 - 4 = 43\neq 0,$$

$$detA_1=\begin{vmatrix}
10 & -1 & 5\\ 
-2 & 1 & -3\\ 
1 & 4 & 1
\end{vmatrix}=
10\begin{vmatrix}
1 & -3\\ 
4 & 1 
\end{vmatrix}
-2\begin{vmatrix}
-1 & 5\\ 
4 & 1 
\end{vmatrix}+
\begin{vmatrix}
-1 & 5 \\ 
1 & -3
\end{vmatrix}=10(1 \cdot 1-3\cdot (-4))-2(-1\cdot 1-5\cdot 4)+(-1\cdot (-3)-5\cdot 1)= 130 -42 - 2 = 86\neq 0,$$

$$detA_2=\begin{vmatrix}
2 & 10 & 5\\ 
1 & -2 & -3\\ 
2 & 1 & 1
\end{vmatrix}=2*(-2)*1 + 10*(-3)*2 + 1*1*5 - (-2)*2*5 - 2*1*(-3) - 1*1*10 = -4 -60 + 5 +20+6 - 10 = -43 $$

$$detA_2=\begin{vmatrix}
2 & -1  & 10 \\ 
1 & 1 &-2 & \\ 
2 & 4 & 1
\end{vmatrix}=2*1*1 + (-1)*(-2)*2 +10*4*1 - 10*2*1 -(-2)*4*2 - 1*1*(-1)= 2 +4 +40 - 20 +16 +1 = 43 $$

In [ ]:
import numpy as np

a = np.array([[2,-1,5], [1,1,-3], [2,4,1]])
a_1 = np.array([[10,-1,5], [-2,1,-3], [1,4,1]])
a_2 = np.array([[2,10,5], [1,-2,-3], [2,1,1]])
a_3 = np.array([[2,-1,10], [1,1,-2], [2,4,1]])

print(f'Определитель A:\n{np.linalg.det(a):.0f}')
print(f'Определитель A1:\n{np.linalg.det(a_1):.0f}')
print(f'Определитель A2:\n{np.linalg.det(a_2):.0f}')
print(f'Определитель A3:\n{np.linalg.det(a_3):.0f}')

Определитель A:
43
Определитель A1:
86
Определитель A2:
-43
Определитель A3:
43


Найдем решение

$$x_{1} = \frac{detA_{1}}{detA} = \frac{86}{43}=2,$$

$$x_{2} = \frac{detA_{2}}{detA} = \frac{-43}{43}=-1$$

$$x_{3} = \frac{detA_{3}}{detA} = \frac{43}{43}=1$$

__2*.__ Найти $L$-матрицу $LU$-разложения для матрицы коэффициентов:

   а)$$\begin{pmatrix}
1 & 2 & 4 \\ 
2 & 9 & 12 \\ 
3 & 26 & 30
\end{pmatrix}$$
    
   б)$$\begin{pmatrix}
1 & 1 & 2 & 4\\ 
2 & 5 & 8 & 9\\ 
3 & 18 & 29 & 18\\
4 & 22 & 53 & 33
\end{pmatrix}$$

а)$$\begin{pmatrix}
1 & 2 & 4 \\ 
2 & 9 & 12 \\ 
3 & 26 & 30
\end{pmatrix}$$ 

Отнимем первую строку, умноженную на 2 от второй, и умноженную на 3 от третьей

$$\begin{pmatrix}
1 & 2 & 4 \\ 
0 & 5 & 4 \\ 
0 & 20 & 18
\end{pmatrix}
$$

$$М_1 = \begin{pmatrix}
1 & 0 & 0 \\ 
-2 & 1 & 0 \\ 
-3 & 0 & 0
\end{pmatrix}
$$

Отнимем от третьей строки вторую, умноженную на 4:

$$\begin{pmatrix}
1 & 2 & 4 \\ 
0 & 5 & 4 \\ 
0 & 0 & 2
\end{pmatrix}
$$

$$М_2 = \begin{pmatrix}
1 & 0 & 0 \\ 
0 & 1 & 0 \\ 
0 & -4 & 1
\end{pmatrix}
$$

Следовательно

$$L = \begin{pmatrix}
1 & 0 & 0 \\ 
2 & 1 & 0 \\ 
3 & 4 & 1
\end{pmatrix}
$$

$$U = \begin{pmatrix}
1 & 2 & 4 \\ 
0 & 5 & 4 \\ 
0 & 0 & 2
\end{pmatrix}
$$

б)$$\begin{pmatrix}
1 & 1 & 2 & 4\\ 
2 & 5 & 8 & 9\\ 
3 & 18 & 29 & 18\\
4 & 22 & 53 & 33
\end{pmatrix} \sim 
\begin{pmatrix}
1 & 1 & 2 & 4\\ 
0 & 3 & 4 & 1\\ 
0 & 15 & 23 & 6\\
0 & 18 & 45 & 17
\end{pmatrix} \sim 
\begin{pmatrix}
1 & 1 & 2 & 4\\ 
0 & 3 & 4 & 1\\ 
0 & 0 & 3 & 1\\
0 & 0 & 21 & 11
\end{pmatrix} \sim
\begin{pmatrix}
1 & 1 & 2 & 4\\ 
0 & 3 & 4 & 1\\ 
0 & 0 & 3 & 1\\
0 & 0 & 0 & 4
\end{pmatrix}$$



$$L = \begin{pmatrix}
1 & 0 & 0 & 0\\ 
2 & 1 & 0 & 0\\ 
3 & 5 & 1 & 0\\
4 & 6 & 7 & 1
\end{pmatrix}
$$

$$U = \begin{pmatrix}
1 & 1 & 2 & 4\\ 
0 & 3 & 4 & 1\\ 
0 & 0 & 3 & 1\\
0 & 0 & 0 & 4
\end{pmatrix}
$$

In [ ]:
l = np.array([[1,0,0, 0], [2,1,0, 0], [3,5,1, 0], [4,6,7, 0]])
u = np.array([[1,1,2, 4], [0,3,4, 1], [0,0,3, 1], [0,0,0, 4]])

print(f'Матрица LU:\n{np.dot(l, u)}')

Матрица LU:
[[ 1  1  2  4]
 [ 2  5  8  9]
 [ 3 18 29 18]
 [ 4 22 53 29]]


__3*.__ Решить систему линейных уравнений методом $LU$-разложения

$$\begin{cases}
2x_{1}+x_{2}+3x_{3}=1 \\
11x_{1}+7x_{2}+5x_{3}=-6 \\
9x_{1}+8x_{2}+4x_{3}=-5
\end{cases}$$

$$\begin{pmatrix}
2 & 1 & 3 \\ 
11 & 7 & 5\\ 
9 & 8 & 4
\end{pmatrix} \sim 
\begin{pmatrix}
2 & 1 & 3 \\ 
0 & 1.5 & -11.5\\ 
0 & 3.5 & 9.5
\end{pmatrix} 
\sim 
\begin{pmatrix}
2 & 1 & 3 \\ 
0 & 1.5 & -11.5\\ 
0 & 0 & 52/3
\end{pmatrix}$$

$$\begin{pmatrix}
1 & 0 & 0 \\ 
11/2 & 1 & 0\\ 
9/2 & 7/3 & 1
\end{pmatrix}$$

In [ ]:
u = np.array([[2,1,3], [0,1.5,-11.5], [0,0, 52/3]])
l = np.array([[1,0,0], [11/2,1,0], [9/2, 7/3, 1]])

print(f'Матрица LU:\n{np.dot(l, u )}')

Матрица LU:
[[ 2.  1.  3.]
 [11.  7.  5.]
 [ 9.  8.  4.]]


Решаем уравнение $Ly = b$:

$$y_1 = 1$$
$$1*11/2 + y_2 = -6 \Leftrightarrow y_2 = - 11.5$$
$$1*9/2  -11.5*7/3 +y_3 = -5 \Leftrightarrow y_3 = 52/3$$

In [ ]:
l = np.array([[1,0,0], [11/2,1,0], [9/2, 7/3, 1]])
b = np.array([1, -6, -5])

print(f'Решение {np.linalg.solve(l, b)}')

Решение [  1.         -11.5         17.33333333]


Решаем уравнение $Ux = y$:

$$52/3x_3 = 52/3 \Leftrightarrow x_3=1$$
$$1.5x_2 - 11.5 = -11.5 \Leftrightarrow x_2 = 0$$
$$2x_1 + 0 + 3 = 1 \Leftrightarrow x_1 = -1 $$

In [ ]:
u = np.array([[2,1,3], [0,1.5,-11.5], [0,0, 52/3]])
b = np.array([1, -11.5, 52/3])

print(f'Решение {np.linalg.solve(u, b)}')

Решение [-1.  0.  1.]


__4*.__ Решить систему линейных уравнений методом Холецкого

$$\begin{cases}
81x_{1}-45x_{2}+45x_{3}=531 \\
-45x_{1}+50x_{2}-15x_{3}=-460 \\
45x_{1}-15x_{2}+38x_{3}=193
\end{cases}$$

Произведем разложение на $LL^{T}$:

$$l_{11}=\sqrt{a_{11}}=\sqrt{81} = 9,$$
$$l_{21}=\frac{a_{21}}{l_{11}}=\frac{-45}{9} = -5,$$
$$l_{31}=\frac{a_{31}}{l_{11}}=\frac{45}{9} = 5,$$

$$l_{22}=\sqrt{a_{22}-l_{21}^{2}}=\sqrt{50 - 25}=5,$$
$$l_{32}=\frac{1}{l_{22}}\left ( a_{32}-l_{21}l_{31} \right)=\frac{1}{5}\left ( -15 - (-5)\cdot 5 \right )= 2,$$

$$l_{33}=\sqrt{a_{33}-l_{31}^{2}-l_{32}^{2}}=\sqrt{38-25-4}=3.$$

Получили матрицу 

$$L = \begin{pmatrix}
9 & 0 & 0 \\ 
-5 & 5 & 0 \\ 
5 & 2 & 3
\end{pmatrix}, 
\; \; 
L^{T} = \begin{pmatrix}
9 & -5 & 5 \\ 
0 & 5 & 2\\ 
0 & 0 & 3
\end{pmatrix}.$$

Решим систему $Ly=b:$



$$y_{1} = 531/9 = 59,$$

$$-5*59 +5y_{2}= -460, y_2 = -33$$

$$5*59 + 2*(-33) +3y_{3} = 193, y_3 = -12.$$

In [ ]:
u = np.array([[9,0,0], [-5,5,0], [5,2,3]])
b = np.array([531, -460, 193])

print(f'Решение {np.linalg.solve(u, b)}')

Решение [ 59. -33. -12.]


И решим систему $L^{T}x=y:$


$$x_{3}=-4,$$

$$5x_{2}-2*(-4)=-33, x_2 = -5$$

$$9x_{1} - 5*(-5) + 5*(-4)=59, x_1=6.$$

In [ ]:
u = np.array([[9,0,0], [-5,5,0], [5,2,3]])
b = np.array([59, -33, -12])

print(f'Решение {np.linalg.solve(u.T, b)}')

Решение [ 6. -5. -4.]
