__1.__ Найти собственные векторы и собственные значения для линейного оператора, заданного матрицей

$$A=\begin{pmatrix}
-1 & -6\\ 
2 & 6
\end{pmatrix}.$$

Посчитаем характеристический многочлен:

$\begin{vmatrix}
-1-\lambda & -6\\ 
2 & 6- \lambda
\end{vmatrix} = (-1-\lambda)(6-\lambda) + 12 = \lambda^2-5\lambda+6.$


$\lambda_1 = 2, \space \lambda_2 = 3$

Находим собственные вектора:


$\lambda = 2$
$$\begin{pmatrix}
-1-2 & -6\\ 
2 & 6-2
\end{pmatrix}
\begin{pmatrix}
x_{1}\\ 
x_{2}
\end{pmatrix}=
\begin{pmatrix}
0\\ 
0
\end{pmatrix}.
$$


$$\begin{cases}
-3x_{1}-6x_{2}= 0 \\
2x_{1}+4x_{2}= 0
\end{cases} \sim  \begin{cases}
x_{1} = 2 , \\
x_{2}= -1.
\end{cases}$$ 


$\lambda = 3$
$$\begin{pmatrix}
-1-3 & -6\\ 
2 & 6-3
\end{pmatrix}
\begin{pmatrix}
x_{1}\\ 
x_{2}
\end{pmatrix}=
\begin{pmatrix}
0\\ 
0
\end{pmatrix}.
$$


$$\begin{cases}
-4x_{1}-6x_{2}= 0 \\
2x_{1}+3x_{2}= 0
\end{cases} \sim  \begin{cases}
x_{1} = 3 , \\
x_{2}= -2.
\end{cases}$$ 


In [ ]:
import numpy as np
np.set_printoptions(precision=2, suppress=True)

a = np.array([[-1, -6], [2, 6]])
w, v = np.linalg.eig(a)

print(f'Матрица A:\n{a}')
print(f'Собственные значения:\n{w}')
print(f'Собственные векторы:\n{v}')

Матрица A:
[[-1 -6]
 [ 2  6]]
Собственные значения:
[2. 3.]
Собственные векторы:
[[-0.89  0.83]
 [ 0.45 -0.55]]


__2.__ Дан оператор поворота на 180 градусов, задаваемый матрицей 

$$A=\begin{pmatrix}
-1 & 0\\ 
0 & -1
\end{pmatrix}.$$

Показать, что __любой__ вектор является для него собственным.


Рассмотрим вектор: $(a,b)$, где a и b - любые.
Нетрудно заметить, что его собственное значение равно -1.

$$\begin{pmatrix}
-1 & 0\\ 
0 & -1
\end{pmatrix}
\begin{pmatrix}
a\\ 
b
\end{pmatrix}=
-1
\begin{pmatrix}
a\\ 
b
\end{pmatrix}.
$$

Равенство верно при любых a и b.



In [ ]:
a = np.array([[-1, 0], [0, -1]])
w, v = np.linalg.eig(a)

print(f'Матрица A:\n{a}')
print(f'Собственные значения:\n{w}')
print(f'Собственные векторы:\n{v}')

Матрица A:
[[-1  0]
 [ 0 -1]]
Собственные значения:
[-1. -1.]
Собственные векторы:
[[1. 0.]
 [0. 1.]]


__3.__ Пусть линейный оператор задан матрицей

$$A=\begin{pmatrix}
1 & 1\\ 
-1 & 3
\end{pmatrix}.$$

Установить, является ли вектор $x=(1,1)$ собственным вектором этого линейного оператора.

$$\begin{pmatrix}
1 & 1\\ 
-1 & 3
\end{pmatrix}
\begin{pmatrix}
1\\ 
1
\end{pmatrix}=
\lambda
\begin{pmatrix}
1\\ 
1
\end{pmatrix}.
$$

$$\Rightarrow
\begin{cases}
\lambda=2\\
\lambda=2
\end{cases}
\Rightarrow
\lambda=2.$$

Вектор является собственным

In [ ]:
a = np.array([[1, 1], [-1, 3]])
w, v = np.linalg.eig(a)

print(f'Матрица A:\n{a}')
print(f'Собственные значения:\n{w}')
print(f'Собственные векторы:\n{v}')

Матрица A:
[[ 1  1]
 [-1  3]]
Собственные значения:
[2. 2.]
Собственные векторы:
[[ 0.71 -0.71]
 [ 0.71 -0.71]]


__4.__ Пусть линейный оператор задан матрицей

$$A=\begin{pmatrix}
0 & 3 & 0\\ 
3 & 0 & 0\\
0 & 0 & 3
\end{pmatrix}.$$

Установить, является ли вектор $x=(3, -3, -4)$ собственным вектором этого линейного оператора.

$$\begin{pmatrix}
0 & 3 & 0\\ 
3 & 0 & 0 \\
0 & 0 & 3
\end{pmatrix}
\begin{pmatrix}
3\\ 
-3 \\
-4
\end{pmatrix}=
\lambda
\begin{pmatrix}
3\\ 
-3 \\
-4
\end{pmatrix}.
$$

$$\Rightarrow
\begin{cases}
3\lambda=-9\\
-3\lambda=9 \\
-4\lambda = -12
\end{cases}
\Rightarrow
\begin{cases}
\lambda=-3 \\
\lambda = 3
\end{cases}$$

Вектор не является собственным

In [ ]:
a = np.array([[0, 3, 0], [3, 0, 0], [0, 0, 3]])
w, v = np.linalg.eig(a)

print(f'Матрица A:\n{a}')
print(f'Собственные значения:\n{w}')
print(f'Собственные векторы:\n{v}')

Матрица A:
[[0 3 0]
 [3 0 0]
 [0 0 3]]
Собственные значения:
[ 3. -3.  3.]
Собственные векторы:
[[ 0.71 -0.71  0.  ]
 [ 0.71  0.71  0.  ]
 [ 0.    0.    1.  ]]


$$ \begin{pmatrix}
6\\ 
2 \\
0 \\
0 
\end  {pmatrix} + a_1 \cdot
\begin{pmatrix}
-3/2\\ 
-1/2\\
1 \\
0 
\end  {pmatrix} + a_2 \cdot
\begin{pmatrix}
-1\\ 
-2\\
0 \\
1 
\end  {pmatrix}$$