In [1]:
# Подключение библиотек
import numpy as np

<h1 align='center' style="color:#2E86C1 ">1. Многомерные массивы </h1>

## Создание массивов

In [2]:
# Создадим саисок из 10 элементов
a = [i for i in range(10)]
a

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [3]:
# Из списка делаем массив Numpy array
b = np.array(a)
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
# Можно сразу создать массив
b = np.array([i for i in range(10)])
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
# Также можно создать из струкруры кортежа
c = (0, 1, 2, 3, 4, 5, 6, 7, 8, 9)
b = np.array(c)
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
type(b)

numpy.ndarray

In [7]:
# Може задать тип элементов массива
b = np.array(a, dtype = float)
b

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

## Взаимодействие с массивами

In [8]:
# Получение 0-го индекса массива
b[0]

0.0

In [9]:
# Просмотр размерности массива
b.ndim

1

In [10]:
# Просмотр размерности массива
b.shape

(10,)

### Создание двумерного массива

In [11]:
b = np.array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
              [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
              [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [12]:
b.shape

(3, 10)

In [13]:
# Просмотр общего количества элементов
b.size

30

### Получение доступа к элементам двумерного массива

In [14]:
# Способ номер 1
b[0][0]

0

In [15]:
# Способ номер 2
b[1, 1]

11

In [16]:
# Срез из двумерного массива
b[0:2, 0:3]

array([[ 0,  1,  2],
       [10, 11, 12]])

In [17]:
b[1:, 5:]

array([[15, 16, 17, 18, 19],
       [25, 26, 27, 28, 29]])

In [18]:
# В данном случае не создаётся новая матрица, 
# а только ссылка на матрицу b
c = b[1:, 5:]

In [19]:
# Для создания нового независимого массива используется метод copy()
# Теперь при изменении массива c, b останется прежним
c = b[1:, 5:].copy()
c

array([[15, 16, 17, 18, 19],
       [25, 26, 27, 28, 29]])

---------------------------

<h1 align='center' style="color:#2E86C1 ">2. Nmpy для линейной алгебры 1</h1>

## Сложение векторов

In [20]:
a = np.array([0, 1, 2, 3, 4])
b = np.array([5, 6, 6, 8, 9])

#### Способ номер 1

In [21]:
# Сложение векторов через '+'
c = a + b
c

array([ 5,  7,  8, 11, 13])

Оператор '+' объединяет списки

In [22]:
x1 = [0, 1, 2, 3, 4]
x2 = [0, 1, 2, 3, 4]

In [23]:
# Производим объединение массивово
x1 + x2

[0, 1, 2, 3, 4, 0, 1, 2, 3, 4]

#### Способ номер 2

In [24]:
# Складывает массивы Numpy поэлементно
с = np.add(a, b)
c

array([ 5,  7,  8, 11, 13])

## Вычитание векторов

In [25]:
a = np.array([5, 4, 8, 4, 3])
b = np.array([3, 5, 7, 1, 3])

#### Способ номер 1

In [26]:
d = a - b
d

array([ 2, -1,  1,  3,  0])

#### Способ номер 2

In [27]:
d = np.subtract(a, b)
d

array([ 2, -1,  1,  3,  0])

При вычитании векторов их размерность должна совпадать

In [28]:
a.shape == b.shape

True

## Умножение векторов

### Умножение вектора на сколяр

In [29]:
a = np.array([5, 4, 8, 4, 3])

In [30]:
c = a * 2
c 

array([10,  8, 16,  8,  6])

Сравним результат умножения натурального числа на спиское

(результат не тот - увелечение длины списка а не умножение вектора на сколяр):

In [31]:
2 * [1, 2, 3]

[1, 2, 3, 1, 2, 3]

In [32]:
# Вариант 1
# Умножение вектора на сколяр
a.dot(-10)

array([-50, -40, -80, -40, -30])

In [33]:
# Вариант 2
np.dot(-10, a)

array([-50, -40, -80, -40, -30])

In [34]:
# Вариант 3
np.multiply(-10, a)

array([-50, -40, -80, -40, -30])

### Скалярное произведение векторов

In [35]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

#### Способ номер 1

In [36]:
# Производим скалярное произведение векторов
sp = a[0] * b[0] + a[1] * b[1] + a[2] * b[2]
sp

32

#### Способ номер 2

In [37]:
a @ b

32

#### Спсоб номер 3

In [38]:
sp = np.dot(a, b)
sp

32

## Операции с матрицами

In [39]:
A = np.array([[0, 1],
              [2, 3],
              [4, 5]])

In [40]:
B = np.array([[6, 7],
              [8, 9],
              [10, 11]])

In [41]:
A.shape
B.shape

(3, 2)

### Сложение матриц

#### Способ номер 1

In [42]:
C = A + B
C

array([[ 6,  8],
       [10, 12],
       [14, 16]])

#### Спсоб номер 2

In [43]:
C = np.add(A, B)
C

array([[ 6,  8],
       [10, 12],
       [14, 16]])

### Умножение матрицы на скаляр

In [44]:
X = np.array([[1, 2],
              [3, 4]])
X

array([[1, 2],
       [3, 4]])

#### Способ номер 1

In [45]:
Y = X * 3
Y

array([[ 3,  6],
       [ 9, 12]])

#### Способ номер 2

In [46]:
Y = np.dot(X, 3)
Y

array([[ 3,  6],
       [ 9, 12]])

--------------

<h1 align='center' style="color:#2E86C1 ">3. Nmpy для линейной алгебры 2</h1>

## Умножение матриц

In [47]:
X1 = np.array([[1, 2],
               [3, 4],
               [5, 6]])

In [48]:
X2 = np.array([[7, 8, 9, 10],
               [11, 12, 13, 14]])

Число столбцов первой матрицы должно равняться числу строк второй матрицы:

In [49]:
X1.shape[1] == X2.shape[0]

True

In [50]:
X1.shape, X2.shape

((3, 2), (2, 4))

In [51]:
Z = np.dot(X1, X2)
Z

array([[ 29,  32,  35,  38],
       [ 65,  72,  79,  86],
       [101, 112, 123, 134]])

## Модуль numpy.linalg: возведение матрицы в квадрат

In [52]:
A = np.array([[0, 1, 2],
              [3, 4, 5],
              [6, 7, 8]])

#### Способ номер 1

In [53]:
A_square = np.dot(A, A)
A_square

array([[ 15,  18,  21],
       [ 42,  54,  66],
       [ 69,  90, 111]])

#### Способ номер 2

In [54]:
A_square = np.linalg.matrix_power(A, 2)
A_square

array([[ 15,  18,  21],
       [ 42,  54,  66],
       [ 69,  90, 111]])

## Создание еденичной матрицы

In [55]:
I = np.eye(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Умножение матрицы на еденичную

In [56]:
A = np.array([[1, 2],
              [3, 4],
              [5, 6]])

#### Случай 1

In [57]:
I = np.eye(2)
I

array([[1., 0.],
       [0., 1.]])

In [58]:
np.dot(A, I)

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

#### Случай 2

In [59]:
I = np.eye(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [60]:
np.dot(I, A)

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

## Транспонирование матрицы

In [61]:
A = np.array([[11, 13],
              [16, 9],
              [8, 15]])

#### Способ номер 1

In [62]:
At = A.transpose()
At

array([[11, 16,  8],
       [13,  9, 15]])

#### Способ номер 2

In [63]:
At = A.T
At

array([[11, 16,  8],
       [13,  9, 15]])

Расмотрим матрицы X и Y:

In [64]:
X = np.array([[1, 2],
              [3, 4],
              [5, 6]])

In [65]:
Y = np.array([[0, 1],
              [3, 4],
              [6, 7],
              [2, 5]])

In [66]:
Yt = Y.T
Yt

array([[0, 3, 6, 2],
       [1, 4, 7, 5]])

In [67]:
np.dot(X, Yt)

array([[ 2, 11, 20, 12],
       [ 4, 25, 46, 26],
       [ 6, 39, 72, 40]])

## Вычисление определителя и ранга матрицы

In [68]:
A = np.array([[0, 1, 2],
              [3, 4, 5],
              [6, 7, 8]])

In [69]:
np.linalg.det(A)

0.0

In [70]:
np.linalg.matrix_rank(A)

2

## Вычисление обратной матрицы

In [71]:
B = np.array([[7, 4, 5],
              [8, 3, 2],
              [6, 10, 12]])

In [72]:
B_inv = np.linalg.inv(B)
B_inv

array([[ 0.18604651,  0.02325581, -0.08139535],
       [-0.97674419,  0.62790698,  0.30232558],
       [ 0.72093023, -0.53488372, -0.12790698]])

In [73]:
B_inv2 = np.linalg.inv(B_inv)
B_inv2

array([[ 7.,  4.,  5.],
       [ 8.,  3.,  2.],
       [ 6., 10., 12.]])

__________________

<h1 align='center' style="color:#2E86C1 ">4. Генерирование массивов с заданными свойствами</h1>

## Автоматическое создание массивов

In [74]:
# Создание массива из нулей, размерностью с 3 строками и 4 столбцами
a = np.zeros((3, 4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [75]:
# Аналог выше, только из едениц
a = np.ones((5, 3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

Последовательность с шагом 2

In [76]:
# Создание последовательности чисел
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

С обратным шагом

In [77]:
# Создание последовательности чисел
np.arange(10, 0, -2)

array([10,  8,  6,  4,  2])

Дробный шаг

In [78]:
np.arange(0, 10, 0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8,
       3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 5. , 5.1,
       5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1, 6.2, 6.3, 6.4,
       6.5, 6.6, 6.7, 6.8, 6.9, 7. , 7.1, 7.2, 7.3, 7.4, 7.5, 7.6, 7.7,
       7.8, 7.9, 8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7, 8.8, 8.9, 9. ,
       9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9])

**numpy.linspace** - то же самое, но нужно учитывать, что правая граница (9.9)будет включена

Вместо шага указывается число элементов (100)

In [79]:
np.linspace(0, 9.9, 100)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8,
       3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 5. , 5.1,
       5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1, 6.2, 6.3, 6.4,
       6.5, 6.6, 6.7, 6.8, 6.9, 7. , 7.1, 7.2, 7.3, 7.4, 7.5, 7.6, 7.7,
       7.8, 7.9, 8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7, 8.8, 8.9, 9. ,
       9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9])

**numpy.logspace** - обе границы включены, указываем не сами числа, а степени числа 10:

In [80]:
# np.logspace(от, до, количество цифр)
np.logspace(0, 3, 4)

array([   1.,   10.,  100., 1000.])

## Генерация случайных чисел

**numpy.random.sample** - случайные числа с равномерным распределением в промежутке [0.0, 1.0)

Если не задать аргумент, то получим случайное число

In [81]:
np.random.sample()

0.32541013741202873

Одномерный массив из 3 чисел:

In [82]:
np.random.sample(3)

array([0.50571066, 0.52704553, 0.5674507 ])

Двумерный массив 2х3:

In [83]:
np.random.sample((2, 3))

array([[0.28637973, 0.44493776, 0.27824797],
       [0.3798958 , 0.56572031, 0.70220498]])

**numpy.random.randn** - случайные числа с нормальным распределением

(среднее значение = 0, среднеквадратичное отклонение = 1)

In [84]:
np.random.randn(3, 4)

array([[-2.23161064,  0.80304255, -1.24505322,  0.99151305],
       [ 0.22867007,  0.23636691, -1.83378502,  0.48808535],
       [-0.48814263, -0.49911813,  0.26691223, -1.31786027]])

**numpy.random.randint** - массив из целых числел.

Например, одномерный массив из 10 целых чисел в промежутке [0, 100):

In [85]:
np.random.randint(0, 100, 10)

array([ 5, 39, 72, 45,  3, 27, 98, 58, 51, 77])

Двумерный массив 3х4 из случайных целых чисел в промежутке [0, 10)

In [86]:
np.random.randint(0, 10, (3, 4))

array([[5, 0, 3, 8],
       [6, 7, 4, 0],
       [6, 5, 5, 0]])

**numpy.random.choice** - случайный выбор элементов из массива

In [87]:
b = np.array([1, 5, 2, 7, 3, 8, 6, 4])

In [88]:
np.random.choice(b)

6

In [89]:
np.random.choice(b, 3)

array([1, 6, 8])

**numpy.random.seed** - инциализация генератора случайных чисел

In [90]:
np.random.seed(42)

In [91]:
np.random.randint(0, 10, 3)

array([6, 3, 7])

## Изменение формы массива

In [92]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

Получение двумерного массива из 3х4

In [93]:
a.reshape(3, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [94]:
# Можно указать требуемое число строк, а вместо числа столбцов поставить - 1
np.reshape(a, (3, -1))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

#### Автоматическое получение многомерного массива

In [95]:
# inplace
a.resize(3, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

#### Атоматическое получение одномерного массива

In [96]:
a = a.flatten()
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

## Соединение массивов

In [97]:
a = np.zeros((2, 3))
a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [98]:
b = np.ones((2, 3))
b

array([[1., 1., 1.],
       [1., 1., 1.]])

#### Соединение строк (вертикально)

In [99]:
# Вариант 1
v = np.vstack((a, b))
v

array([[0., 0., 0.],
       [0., 0., 0.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [100]:
# Вариант 2
np.concatenate((a, b), axis = 0)

array([[0., 0., 0.],
       [0., 0., 0.],
       [1., 1., 1.],
       [1., 1., 1.]])

#### Соединение столбцов (горизонтально)

In [101]:
# Вариант 1
h = np.hstack((a, b))
h

array([[0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.]])

In [102]:
# Вариант 2
np.concatenate((a, b), axis = 1)

array([[0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.]])

#### Соединение в глубину (в третьем измерении)

In [103]:
d = np.dstack([a, b])
d

array([[[0., 1.],
        [0., 1.],
        [0., 1.]],

       [[0., 1.],
        [0., 1.],
        [0., 1.]]])

______________________________

<h1 align='center' style="color:#2E86C1 ">5. Функции для работы с данными</h1>

## Выбор данных из массива

In [104]:
a = np.random.randint(0, 20, 10)
a

array([ 6, 18, 10, 10,  3,  7,  2,  1, 11,  5])

In [105]:
# Условие выбора 
a[a > 10]

array([18, 11])

In [106]:
# Два условия выбора
a[(a > 10) & (a % 2 == 0)]

array([18])

In [107]:
# Два условия выбора
a[(a > 10) | (a % 3 == 0)]

array([ 6, 18,  3, 11])

**numpy.where** - первый вариант применения 

In [108]:
a

array([ 6, 18, 10, 10,  3,  7,  2,  1, 11,  5])

In [109]:
# Возвращает индексы чисел, удовлетворяющих условию
np.where(a > 10)

(array([1, 8], dtype=int64),)

In [110]:
a[np.where(a > 10)]

array([18, 11])

**numpy.where**- второй вариант применения

In [111]:
a = [1, 4, 7]
b = [9, 2, 5]

In [112]:
# Если в условии True, то берем элемент из массива a,
# Если False - то из b
np.where([True, False, True], a, b)

array([1, 2, 7])

## Сортировка

In [113]:
a = np.array([[1, 3, 9, 9],
              [5, 0, 1, 5],
              [2, 7, 3, 5]])

In [114]:
# Сортировка массива по нулевому столбцу
a[[0, 2, 1], :]

array([[1, 3, 9, 9],
       [2, 7, 3, 5],
       [5, 0, 1, 5]])

In [115]:
# Сделаем это автоматически:
a.argsort(axis = 0)

array([[0, 1, 1, 1],
       [2, 0, 2, 2],
       [1, 2, 0, 0]], dtype=int64)

In [116]:
# Сортировка только по нулевому столбцу
a[:, 0].argsort()

array([0, 2, 1], dtype=int64)

In [117]:
# Создаём итоговую конструкцию
a[a[:, 0].argsort(), :]

array([[1, 3, 9, 9],
       [2, 7, 3, 5],
       [5, 0, 1, 5]])

## Случайное перемешивание массивов

#### Одномерные массивы

In [118]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [119]:
# inplace - на месте
np.random.shuffle(a)
a

array([5, 2, 7, 6, 8, 9, 3, 0, 4, 1])

In [120]:
a = np.arange(12).reshape(4, 3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [121]:
# inplace
np.random.shuffle(a)
a

array([[ 3,  4,  5],
       [ 0,  1,  2],
       [ 9, 10, 11],
       [ 6,  7,  8]])

## Математические действия с массивами

### Применение математических функция ко всему массиву

In [122]:
a = np.arange(1, 7).reshape(2, 3)
a

array([[1, 2, 3],
       [4, 5, 6]])

#### Вычисление натурального логарифма для всех элементов массива

In [123]:
np.log(a)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947]])

#### Экспонента

In [124]:
np.exp(a)

array([[  2.71828183,   7.3890561 ,  20.08553692],
       [ 54.59815003, 148.4131591 , 403.42879349]])

#### Сумма всех элементов массива

In [125]:
a.sum()

21

In [126]:
# 'axis = 0' - сумма элементов столбцов
a.sum(axis = 0)

array([5, 7, 9])

In [127]:
# 'axis = 1' - сумма элементов строк
a.sum(axis = 1)

array([ 6, 15])

#### Прибавление к массиву

In [128]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [129]:
#### К каждому элементу массива прибавится 10
10 + a

array([[11, 12, 13],
       [14, 15, 16]])

### Поэлементное (не матричное) умножение

In [130]:
a = np.arange(12).reshape(3, -1)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [131]:
b = np.arange(12, 24).reshape(-1, 4)
b

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [132]:
# Производим поэлементное умножение
a * b

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

## Broadcasting (на примере сложения)

In [133]:
a = np.array([[2, 5],
              [3, 4],
              [6, 1]])

#### Случай 1 - совпадает только число столбцов

In [134]:
b = np.array([1, 2])

In [135]:
# К каждой строке массива a прибавляется строка из массива b 
a + b

array([[3, 7],
       [4, 6],
       [7, 3]])

#### Случай 2 - совпадает только число строк

In [136]:
c = np.array([[1],
              [2],
              [3]])

In [137]:
a

array([[2, 5],
       [3, 4],
       [6, 1]])

In [138]:
# Аналогично, только со столбцами
a + c

array([[3, 6],
       [5, 6],
       [9, 4]])

## Статистические функции

In [139]:
a = np.random.randint(0, 12, (3, 4))
a

array([[ 9, 11, 11,  2],
       [11,  6,  3,  8],
       [ 2,  4,  2,  6]])

#### Минимальное значение

In [140]:
a.min()

2

In [141]:
# Минимальное значение для каждого столбца
a.min(axis = 0)

array([2, 4, 2, 2])

#### Максимальное значение

In [142]:
# Максимальное значение для каждой строки
a.max(axis = 1)

array([11, 11,  6])

#### Среднее значение

In [143]:
# Среднее значение для каждого столбца
a.mean(axis = 0)

array([7.33333333, 7.        , 5.33333333, 5.33333333])

#### Среднее квадратичное отклонение

In [144]:
# Среднее квадратичное отклонение для каждого столбца
a.std(axis = 0)

array([3.8586123 , 2.94392029, 4.02768199, 2.49443826])

## Запись и чтение массива из файла

In [145]:
# Сохраниение
np.save('a.npy', a)

In [146]:
# Выгружаем из файла массив
b = np.load('a.npy')

In [147]:
b

array([[ 9, 11, 11,  2],
       [11,  6,  3,  8],
       [ 2,  4,  2,  6]])