# **Первая часть**

__1.__ Установить, какие произведения матриц $AB$ и $BA$ определены, и найти размерности полученных матриц:

   а) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$;
    
   б) $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$;
    
   в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$;
    
   г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$.

Решение:

а) $AB, BA$ - не определены

б) $AB$ - определена, $AB$ - матрица $2 \times 3$

в) $AB$ - матрица $8 \times 8$,  $BA$ - матрица $3 \times 3$

г)$AB, BA$ - матрицы $4 \times 4$

__2.__ Найти сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$

Решение:

$$A+B = \begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix} + \begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix} = \begin{pmatrix}
1+4 & -2-1\\ 
3+0 & 0+5
\end{pmatrix} = \begin{pmatrix}
5 & -3\\ 
3 & 5
\end{pmatrix}$$
<br><br>
$$A \times B = \begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix} \times \begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix} = \begin{pmatrix}
1*4+ (-2)*0 & 1*(-1)+(-2)*5\\ 
3*4+0*0 & 3*(-1)+0*5
\end{pmatrix} = \begin{pmatrix}
4 & -11\\ 
12 & -3
\end{pmatrix}$$

In [ ]:
import numpy as np


a = np.array([[1, -2], [3, 0]])
b = np.array([[4, -1], [0, 5]])

print(f'Матрица A\n{a}\n')
print(f'Матрица B\n{b}\n')
print(f'Матрица A+B\n{a+b}\n')
print(f'Матрица AB\n{np.dot(a, b)}')


Матрица A
[[ 1 -2]
 [ 3  0]]

Матрица B
[[ 4 -1]
 [ 0  5]]

Матрица A+B
[[ 5 -3]
 [ 3  5]]

Матрица AB
[[  4 -11]
 [ 12  -3]]


__3.__ Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$

Решение:

$$3A-2B+4C = 3\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix} - 2\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix} + 4\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix} = \begin{pmatrix}
3*1 - 2*0 +4*2 & 3*7-2*5+4*(-4)\\ 
3*3-2*2+4*1 & 3*(-6)-2*(-1) +4*1
\end{pmatrix} = \begin{pmatrix}
11 & -5\\ 
9 & -12
\end{pmatrix}$$

In [ ]:
a = np.array([[1, 7], [3, -6]])
b = np.array([[0, 5], [2, -1]])
c = np.array([[2, -4], [1, 1]])

print(f'Матрица A\n{a}\n')
print(f'Матрица B\n{b}\n')
print(f'Матрица C\n{c}\n')
print(f'Матрица 3A-2B+4C\n{3*a-2*b+4*c}\n')

Матрица A
[[ 1  7]
 [ 3 -6]]

Матрица B
[[ 0  5]
 [ 2 -1]]

Матрица C
[[ 2 -4]
 [ 1  1]]

Матрица 3A-2B+4C
[[ 11  -5]
 [  9 -12]]



__4.__ Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислить $AA^{T}$ и $A^{T}A$.

Решение:

$A^T = \begin{pmatrix}
4 & 5 & 2\\ 
1 & -2 & 3
\end{pmatrix}$

$AA^T = \begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix} \times \begin{pmatrix}
4 & 5 & 2\\ 
1 & -2 & 3
\end{pmatrix} = \begin{pmatrix}
4*4 +1*1 & 4*5+1*(-2) & 4*2+ 1*3\\ 
5*4+(-2)*1 & 5*5+(-2)*(-2) & 5*2+(-2)*3\\ 
2*4 + 3*1 & 2*5+3*(-2) & 2*2+ 3*3
\end{pmatrix} = \begin{pmatrix}
17 & 18 & 11\\ 
18 & 29 & 4\\ 
11 & 4 & 13
\end{pmatrix}$

$A^TA = \begin{pmatrix}
4 & 5 & 2\\ 
1 & -2 & 3
\end{pmatrix} \times \begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}= \begin{pmatrix}
4*4 + 5*5 +2*2 & 4*1 +5*(-2)+2*3\\ 
1*4+(-2)*5+3*2 & 1*1+(-2)*(-2)+3*3 
\end{pmatrix} = \begin{pmatrix}
45 & 0\\ 
0 & 14
\end{pmatrix}$

In [ ]:
a = np.array([[4,1], [5, -2], [2,3]])

print(f'Матрица A\n{a}\n')
print(f'Матрица A^T\n{a.T}\n')
print(f'Матрица A*A^T\n{np.dot(a, a.T)}\n')
print(f'Матрица A^T*A\n{np.dot(a.T, a)}\n')

Матрица A
[[ 4  1]
 [ 5 -2]
 [ 2  3]]

Матрица A^T
[[ 4  5  2]
 [ 1 -2  3]]

Матрица A*A^T
[[17 18 11]
 [18 29  4]
 [11  4 13]]

Матрица A^T*A
[[45  0]
 [ 0 14]]



__5*.__ Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

In [ ]:
def matrix_multiply(a, b):
  a_column = len(a[0])
  b_string = len(b)

  if a_column != b_string:
    return False
  
  c = []

  for i in range(len(a)):
    c.append([])
    for j in range(len(b[0])):
      c_ij = 0
      for k in range(len(b)):
        c_ij += a[i][k]*b[k][j]
      c[i].append(c_ij)

  return c


a = [[ 4, 1],
 [ 5, -2],
 [ 2, 3]]
b = [[ 4, 5, 2],
 [ 1, -2, 3]]


matrix_multiply(a, b)     

[[17, 18, 11], [18, 29, 4], [11, 4, 13]]

# **Вторая часть**

__1.__ Вычислить определитель:

   a)

$$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix};$$

   б)
    
$$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix};$$
    
   в)

$$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix}.$$

Решение:

а) $$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix} =sinx*sinx - (-cosx)*cosx = 1 $$

б) $$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix} = 4 * \begin{vmatrix}
5 & 1\\ 
0 & 9
\end{vmatrix} - 0 * \begin{vmatrix}
2 & 3\\  
0 & 9
\end{vmatrix} + 0 * \begin {vmatrix}
2 & 3\\ 
5 & 1
\end{vmatrix} = 4 * (5*9 - 1*0)  = 180$$

в) $$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix} = 1*5*9 +7*2*6+4*8*3 - 3*5*7 - 2*4*9 - 1*6*8 = 45+ 84+96 - 105 - 72 - 48 = 0$$

In [ ]:
b = np.array([[4,2,3], [0,5,1], [0,0,9]])
c = np.array([[1,2,3], [4,5,6], [7,8,9]])

print(f'Определитель B:\n{np.linalg.det(b):.0f}')
print(f'Определитель C:\n{np.linalg.det(c):.0f}')

Определитель B:
180
Определитель C:
0


__2.__ Определитель матрицы $A$ равен $4$. Найти:

   а) $det(A^{2})$;
    
   б) $det(A^{T})$;
    
   в) $det(2A)$.

   

Решение:

а) $det(A^{2}) = det(A)\times det(A) = 16$

б) $det(A^T) = det(A) = 4$

с) Если размер матрицы $n \times n$, то

$det(2A) = 2^n \times det(A)$



__3.__  Доказать, что матрица

$$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$$
   
вырожденная.

Решение:

Посчитаем определитель.
$$\begin{vmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{vmatrix} = (-2)*(-14)*13 +4*7*(-3) + 7*6*(-3) - (-3)*(-14)*(-3) - (-2)*6*7 - 4*7*13 = 364 - 84 - 126 + 126 + 84 - 364 = 0$$

In [ ]:
a = np.array([[-2, 7, -3], [4, -14, 6], [-3, 7, 13]])

print(f'Определитель A:\n{np.linalg.det(a):.0f}')

Определитель A:
0


__4.__ Найти ранг матрицы:

   а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix};$

   б) $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}.$

Решение:

а) $rank\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix} = rank \begin{pmatrix}
1 & 1 & 1\\ 
0 & 1 & 2\\ 
0 & 1 & 2
\end{pmatrix} = rank\begin{pmatrix}
1 & 1 & 1\\ 
0 & 1 & 2\\ 
0 & 0 & 0
\end{pmatrix} = 2$

б)$ rank\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}  = rank\begin{pmatrix}
2 & 3 & 5 & 6 \\
0 & 0 & 2 & 1\\ 
0 & 0 & 0 & 1\\ 
0 & 0 & 0 & 0
\end{pmatrix} = 3$

In [ ]:
a = np.array([[1,2,3], [1,1,1], [2,3,4]])
b = np.array([[0,0,2,1], [0,0,2,2], [0,0,4,3], [2,3,5,6]])
r = np.linalg.matrix_rank(a)

print(f'Ранг матрицы: {r}')