# Урок 2. Матрицы и матричные операции
### Методический материал 1

In [77]:
import numpy as np
import random as rd

#### Задание 1
Установить, какие произведения матриц  AB  и  BA  определены, и найти размерности полученных матриц:

1.  __A  — матрица  4×2 ,  B  — матрица  4×2;__
    
__Ответ:__ Произвести умножение матрицы **А** на **В**  и **B** на **А** невозможно, так как количество столбцов матрицы **А** не равно количеству строк матрицы **В**.

    
    

2.  __A  — матрица  2×5 ,  B  — матрица  5×3;__

$A=\begin{pmatrix}
1 & -2 & 6 & 7 & 1\\ 
6 & 5 & 1 & 5 & -4
\end{pmatrix}$ и 
$B=\begin{pmatrix}
9 & 1 & 6\\ 
5 & 1 & 1\\
4 & 7 & 3\\
9 & 0 & 8\\
1 & 2 & 5
\end{pmatrix}$

$AB=\begin{pmatrix}
9 - 10 + 24 + 63 + 1 & 1 - 2 + 42 + 0 + 2 & 6 - 2 + 18 + 56 + 5\\ 
54 + 25 + 4 + 45 - 4 & 6 + 5 + 7 + 0 - 8 & 36 + 5 + 3 + 40 - 20
\end{pmatrix}$ = 
$\begin{pmatrix}
87 & 43 & 83\\
124 & 10 & 64
\end{pmatrix}$

__Ответ:__ Если умножить матрицу **A** на матрицу **B**, будет матрица размерностью `3х3`. Матрицу **B** умножить на матриу **А** нельзя, так как количество столбцов матрицы **А** не равно количеству строк матрицы **В**.

**Выполняем проверку через Numpy:**

In [33]:
A = np.array([[1, -2, 6, 7, 1], [6, 5, 1, 5, -4]])
B = np.array([[9, 1, 6], [5, 1, 1], [4, 7, 3], [9, 0, 8], [1, 2, 5]])

np.dot(A, B)

array([[ 87,  43,  83],
       [124,  10,  64]])

3.  __A  — матрица  8×3 ,  B  — матрица  3×8;__

В задании 2, рассчёты производились для наглядности.

__Ответ:__ Умножение матрицы **A** на матрицу **B**, даёт матрицу размерностью `8х8`. При умножени матрицы **B** на матрицу **А**, размерность итоговой матрицы составит `3х3`

**Выполним проверку через Numpy:**

In [38]:
A = np.ones((1, 8, 3))[0]
B = np.ones((1, 3, 8))[0]

print(np.dot(A, B).shape)
print(np.dot(B, A).shape)

(8, 8)
(3, 3)


4.  __A  — квадратная матрица  4×4 ,  B  — квадратная матрица  4×4.__

__Ответ:__ Умножение матрицы **A** на матрицу **B**, даёт матрицу размерностью `4х4`. При умножени матрицы **B** на матрицу **А**, размерность итоговой матрицы составит `4х4`

In [39]:
A = np.ones((1, 4, 4))[0]
B = np.ones((1, 4, 4))[0]

print(np.dot(A, B).shape)
print(np.dot(B, A).shape)

(4, 4)
(4, 4)


---
#### Задание 2
Найти сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$

$A + B =\begin{pmatrix}
5 & -3\\ 
3 & 5
\end{pmatrix}$

${A}\cdot{B} =\begin{pmatrix}
4 & -11\\ 
12 & -3
\end{pmatrix}$

**Выполняем проверку через Numpy:**

In [48]:
A = np.array([[1, -2], [3, 0]])
B = np.array([[4, -1], [0, 5]])

print(np.add(A, B))
print(np.dot(A, B))

[[ 5 -3]
 [ 3  5]]
[[  4 -11]
 [ 12  -3]]


---
#### Задание 3
Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$

$3A=\begin{pmatrix}
3 & 21\\ 
9 & -18
\end{pmatrix}$, $2B=\begin{pmatrix}
0 & 10\\ 
4 & -2
\end{pmatrix}$, $4C=\begin{pmatrix}
8 & -16\\ 
4 & 4
\end{pmatrix}$

$3A-2B+4C=\begin{pmatrix}
-5 & 27\\ 
1 & -20
\end{pmatrix}$

**Выполним проверку через Numpy:**

In [65]:
A = np.array([[1, 7], [3, -6]])
B = np.array([[0, 5], [2, -1]])
C = np.array([[2, -4], [1, 1]])

np.subtract(3 * A, 2 * B + 4 * C)

array([[ -5,  27],
       [  1, -20]])

---
#### Задание 4
Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$
Вычислить $AA^{T}$ и $A^{T}A$.

$A^{T}=\begin{pmatrix}
4 & 5 & 2\\ 
1 & -2 & 3
\end{pmatrix}$

**Выполним проверку через Numpy:**

In [70]:
A = np.array([[4, 1], [5, -2], [2, 3]])
A_T = A.T
A_T

array([[ 4,  5,  2],
       [ 1, -2,  3]])

$AA^{T}=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix} \cdot \begin{pmatrix}
4 & 5 & 2\\ 
1 & -2 & 3
\end{pmatrix} = \begin{pmatrix}
16 + 1 & 20 - 2 & 8 + 3\\ 
20 - 2 & 25 + 4 & 10 - 6\\ 
8 + 3 & 10 - 6 & 4 + 9
\end{pmatrix} = \begin{pmatrix}
17 & 18 & 11\\ 
18 & 29 & 4\\
11 & 4 & 13
\end{pmatrix}$

**Выполним проверку через Numpy:**

In [72]:
np.dot(A, A_T)

array([[17, 18, 11],
       [18, 29,  4],
       [11,  4, 13]])

$A^{T}A = \begin{pmatrix}
4 & 5 & 2\\ 
1 & -2 & 3
\end{pmatrix} \cdot \begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix} = \begin{pmatrix}
16 + 25 + 4 & 4 - 10 + 6\\ 
4 - 10 + 6 & 1 + 4 + 9
\end{pmatrix} = \begin{pmatrix}
45 & 0\\ 
0 & 14
\end{pmatrix}$

**Выполним проверку через Numpy:**

In [73]:
np.dot(A_T, A)

array([[45,  0],
       [ 0, 14]])

----
#### Задание 5
Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

**Основная функция**

In [191]:
def dot(A, B):
    if len(A[0]) == len(B):
        return return_matrix(A, B)
    else:
        print('Количество столбцов матрицы А не равно количеству строк матрицы В.')


def return_matrix(A, B):
    matrix = [[] for i in range(len(A))]
    for x in range(len(A)):
        for a in range(len(B[0])):
            s = 0
            for b in range(len(A[0])):
                s += A[x][b] * B[b][a]
            matrix[x].append(s)
    return matrix

**Создание матрицы**

In [200]:
A = [[rd.randint(1, 10) for _ in range(3)] for _ in range(3)]
A

[[6, 8, 1], [2, 7, 1], [5, 4, 10]]

In [201]:
B = [[rd.randint(1, 10) for _ in range(3)] for _ in range(3)]
B

[[10, 10, 8], [7, 5, 4], [2, 3, 1]]

**Проверка работоспособности**

In [202]:
print(dot(A, B))
print(dot(B, A))

[[118, 103, 81], [71, 58, 45], [98, 100, 66]]
[[120, 182, 100], [72, 107, 52], [23, 41, 15]]


In [203]:
print(np.dot(A, B))
print(np.dot(B, A))

[[118 103  81]
 [ 71  58  45]
 [ 98 100  66]]
[[120 182 100]
 [ 72 107  52]
 [ 23  41  15]]


### Методический материал 1


#### Задание 1
Вычислить определитель:

1. $\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix} = {sinx}\cdot{sinx} + {cosx}\cdot{cosx} = 1$


2. $\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix} = ({4}\cdot{5}\cdot{9} + {0}\cdot{0}\cdot{3} + {2}\cdot{1}\cdot{0}) - ({3}\cdot{5}\cdot{0} + {0}\cdot{2}\cdot{9} + {0}\cdot{1}\cdot{4}) = 180$

Можно было воспользоваться свойством матрицы и умножить диагональные элементы. Пример выше используется для наглядности.

**Выполним проверку с использованием Numpy:**

In [222]:
A = np.array([[4, 2, 3], [0, 5, 1], [0, 0, 9]])
np.linalg.det(A)

180.0

3. $\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix} = ({1}\cdot{5}\cdot{9} + {2}\cdot{6}\cdot{7} + {4}\cdot{8}\cdot{3}) - ({7}\cdot{5}\cdot{3} + {4}\cdot{2}\cdot{9} + {8}\cdot{6}\cdot{1}) = 225 - 225 = 0$

**Выполним проверку с использованием Numpy:**

In [223]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
np.linalg.det(A)

-9.51619735392994e-16

---
#### Задание 2
Определитель матрицы $A$ равен $4$. Найти:

   а) $det(A^{2})$;
   
   Если возвести матрицу в квадрат, то и определитель приёдтся возвести в квадрат.
   
   __Ответ:__ `16`
   
   б) $det(A^{T})$;
   
   Определитель транспонированной матрицы равне определителю исходной.
   
   __Ответ:__ `4`
    
   в) $det(2A)$.
   
   Умножение строки или столбца матрицы на число $\lambda$ приведёт к умножению определителя матрицы на то же число.
   Так как мы умножили кажду строку на число $\lambda$, то и определитель требуется умножить на $\lambda$ столько раз, сколько у нас строк.
   
   __Ответ:__ `32`

---
#### Задание 3
Доказать, что матрица

$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix} $
вырожденная.

Найдём определитель матрицы:

$\begin{vmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{vmatrix} = (364 - 126 - 84) - (-126 + 364 - 84)= 364 - 126 - 84 + 126 - 364 + 84 = 0 $


__Ответ:__ Данная матрица является вырожденной.

**Выполним проверку с использованием Numpy:**

In [245]:
A = np.array([[-2, 7, -3], [4, -14, 6], [-3, 7, 13]])
np.linalg.det(A)

0.0

#### Задание 4
Найти ранг матрицы:

   а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix};$

   б) $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}.$